/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109879-g42bf52b4c5-20230219"
#endif /* AVUTIL_FFVERSION_H */
